#ifndef _CONTROLS_H_
#define _CONTROLS_H_ 

#include <wiiuse/wpad.h>

#define TOUCH_SCREEN_CONTROLS_ENABLED 0

#define CONTROLS_ACCEPT WPAD_BUTTON_A
#define CONTROLS_CANCEL WPAD_BUTTON_B
#define CONTROLS_UP 0
#define CONTROLS_DOWN 0
#define CONTROLS_LEFT 0
#define CONTROLS_RIGHT 0
#define CONTROLS_DIRECTION WPAD_BUTTON_B
#define CONTROLS_HORIZONTAL (WPAD_BUTTON_LEFT | WPAD_BUTTON_RIGHT)
#define CONTROLS_VERTICAL (WPAD_BUTTON_UP | WPAD_BUTTON_DOWN)
#define CONTROLS_BUILD_WALL (WPAD_BUTTON_A | WPAD_BUTTON_LEFT | WPAD_BUTTON_RIGHT | WPAD_BUTTON_UP | WPAD_BUTTON_DOWN)
#define CONTROLS_CONTINUE WPAD_BUTTON_A
#define CONTROLS_EXIT WPAD_BUTTON_HOME

#define CONTROLS_KBENTER WPAD_BUTTON_PLUS

void updateControls();
u32 isKeyPressed(u32 key);
u32 isKeyDown(u32 key);
u32 isKeyReleased(u32 key);

#endif
